import { Gift } from './types';

// Wedding Date: February 14, 2026 at 16:00
// Note: Month is 0-indexed in JavaScript Dates (0 = January, 1 = February)
export const WEDDING_DATE = new Date(2026, 1, 14, 17, 0, 0);

// Placeholder image for the couple. Replace with the actual photo URL.
export const COUPLE_PHOTO = "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?q=80&w=2070&auto=format&fit=crop";

// PIX Configuration
// Substitua pela sua chave real e pela URL da imagem do seu QR Code gerado no app do banco
export const PIX_KEY = "(75)992258902"; 
export const PIX_HOLDER_NAME = "Gabriella & Wevelley";
export const PIX_QR_CODE_URL = "https://upload.wikimedia.org/wikipedia/commons/d/d0/QR_code_for_mobile_English_Wikipedia.svg"; // Exemplo placeholder

export const INITIAL_GIFTS: Gift[] = [
  // --- Cama & Banho ---
  {
    id: 'cb-1',
    name: 'Cama Queen',
    description: 'O alicerce dos nossos sonhos e descanso diário.',
    image: 'https://i.pinimg.com/736x/ec/69/dd/ec69ddf0202b3cb30e02e650f66d5039.jpg',
    category: 'Cama & Banho',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cb-2',
    name: 'Jogo de Cama Queen',
    description: 'Toque macio de 600 fios para noites tranquilas.',
    image: 'https://images.unsplash.com/photo-1522771753062-86a9794113db?auto=format&fit=crop&w=800&q=80',
    category: 'Cama & Banho',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cb-3',
    name: 'Jogo de Banho',
    description: 'Para o conforto de um banho relaxante.',
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=800&q=80',
    category: 'Cama & Banho',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cb-4',
    name: 'Par de Travesseiros',
    description: 'Nuvens suaves para apoiar nossos pensamentos.',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?auto=format&fit=crop&w=800&q=80',
    category: 'Cama & Banho',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cb-5',
    name: 'Edredom',
    description: 'Aconchego garantido para os dias mais frios.',
    image: 'https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=800&q=80',
    category: 'Cama & Banho',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cb-6',
    name: 'Cobertor',
    description: 'Um abraço quentinho para nossas maratonas de filmes.',
    image: 'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?auto=format&fit=crop&w=800&q=80',
    category: 'Cama & Banho',
    claimedBy: null,
    claimedByUserId: null,
  },

  // --- Casa & Décor ---
  {
    id: 'cd-1',
    name: 'Abajur',
    description: 'Luz suave para criar uma atmosfera intimista.',
    image: 'https://images.unsplash.com/photo-1513506003011-3b614491215e?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-2',
    name: 'Lixeira Inox',
    description: 'Elegância e organização em cada detalhe.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-3',
    name: 'Jogo de Tapetes',
    description: 'Conforto aos pés em todos os cômodos.',
    image: 'https://images.unsplash.com/photo-1534889156217-d643df14f14a?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-4',
    name: 'Mesa de Escritório',
    description: 'Um espaço dedicado para planejar nosso futuro.',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-5',
    name: 'Impressora',
    description: 'Praticidade para o nosso home office.',
    image: 'https://images.unsplash.com/photo-1612815154858-60aa4c4603e1?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-6',
    name: 'Mesa de Cabeceira',
    description: 'Para apoiar nossos livros e sonhos antes de dormir.',
    image: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-7',
    name: 'Sapateira',
    description: 'Organização para começar o dia com o pé direito.',
    image: 'https://images.unsplash.com/photo-1595515106968-4669865eb770?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-8',
    name: 'Ventilador',
    description: 'Brisas frescas para os dias de verão.',
    image: 'https://images.unsplash.com/photo-1558402529-d2638a7023e9?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-9',
    name: 'Umidificador de Ar',
    description: 'Bem-estar e saúde para o nosso ambiente.',
    image: 'https://images.unsplash.com/photo-1585771724684-382054863d61?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-10',
    name: 'Máquina de Lavar',
    description: 'Cuidado essencial para nossas roupas favoritas.',
    image: 'https://images.unsplash.com/photo-1626806775351-538af710221e?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-11',
    name: 'Tanquinho',
    description: 'Auxílio prático para a lavanderia.',
    image: 'https://images.unsplash.com/photo-1517677208171-0bc12f9ea468?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-12',
    name: 'Aspirador de Pó',
    description: 'Para manter nosso lar sempre impecável.',
    image: 'https://images.unsplash.com/photo-1558317374-a3545eca640e?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-13',
    name: 'Ferro de Passar',
    description: 'Para estarmos sempre alinhados em ocasiões especiais.',
    image: 'https://images.unsplash.com/photo-1512413914633-b5043f4041ea?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-14',
    name: 'Tábua de Passar',
    description: 'O suporte perfeito para o cuidado com as roupas.',
    image: 'https://images.unsplash.com/photo-1453230806017-56d81464b6c5?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-15',
    name: 'Cesto de Roupa',
    description: 'Charme até na organização da lavanderia.',
    image: 'https://images.unsplash.com/photo-1594229658253-34bb3222e967?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  
  {
    id: 'cd-18',
    name: 'Espelho Decorativo',
    description: 'Para refletir a alegria da nossa casa.',
    image: 'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cd-19',
    name: 'Mop de Limpeza',
    description: 'Praticidade moderna para a limpeza diária.',
    image: 'https://images.unsplash.com/photo-1527512860163-5e8a571c4c86?auto=format&fit=crop&w=800&q=80',
    category: 'Casa & Décor',
    claimedBy: null,
    claimedByUserId: null,
  },

  // --- Cozinha ---
  {
    id: 'cz-1',
    name: 'Geladeira',
    description: 'O coração da nossa cozinha, preservando sabores.',
    image: 'https://images.unsplash.com/photo-1571175443880-49e1d58b7270?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-2',
    name: 'Fogão',
    description: 'Onde as receitas de família ganharão vida.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-3',
    name: 'Air Fryer',
    description: 'Sabor e saúde para nossas refeições rápidas.',
    image: 'https://images.unsplash.com/photo-1626162383842-c13f9f31b51e?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-4',
    name: 'Microondas',
    description: 'Facilidade para a correria do dia a dia.',
    image: 'https://images.unsplash.com/photo-1585659722983-3a67520263bc?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-5',
    name: 'Liquidificador',
    description: 'Para sucos frescos e vitaminas matinais.',
    image: 'https://images.unsplash.com/photo-1570222094114-28a9d88a2ef5?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-6',
    name: 'Jogo de Panelas',
    description: 'Os instrumentos para nossa arte culinária.',
    image: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-7',
    name: 'Panela de Pressão',
    description: 'Segurança e rapidez no preparo dos clássicos.',
    image: 'https://images.unsplash.com/photo-1583944692716-e822081d6683?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-8',
    name: 'Jogo de Talheres',
    description: 'Para servir com elegância em todos os jantares.',
    image: 'https://images.unsplash.com/photo-1581643447953-d955502c462e?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-9',
    name: 'Jogo de Copos',
    description: 'Para brindarmos as pequenas vitórias.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },

  {
    id: 'cz-11',
    name: 'Filtro de Água',
    description: 'Água pura e fresca sempre à mão.',
    image: 'https://images.unsplash.com/photo-1563812836-4d2629b1d9df?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-12',
    name: 'Faqueiro Especial',
    description: 'Peças finas para ocasiões especiais.',
    image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-13',
    name: 'Cuscuzeira',
    description: 'Tradição e sabor no nosso café da manhã.',
    image: 'https://images.unsplash.com/photo-1586546376510-9118c7c999b1?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-14',
    name: 'Frigideira Antiaderente',
    description: 'Perfeita para grelhados e tapiocas.',
    image: 'https://images.unsplash.com/photo-1593060132560-8430e70da394?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-15',
    name: 'Forno Elétrico',
    description: 'Assados perfeitos e gratinados deliciosos.',
    image: 'https://images.unsplash.com/photo-1586208958839-06c1719533bd?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-16',
    name: 'Processador de Alimentos',
    description: 'Agilidade no preparo de receitas complexas.',
    image: 'https://images.unsplash.com/photo-1585839230553-62506e30f1d7?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-17',
    name: 'Jogo de Pano de Prato',
    description: 'Charme e utilidade pendurados na copa.',
    image: 'https://images.unsplash.com/photo-1574719266710-d0f55df0521e?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-18',
    name: 'Formas e Assadeiras',
    description: 'Para bolos, tortas e momentos doces.',
    image: 'https://images.unsplash.com/photo-1504930268766-d715458023e8?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-19',
    name: 'Utensílios de Cozinha',
    description: 'Conchas, espátulas e colheres para o dia a dia.',
    image: 'https://images.unsplash.com/photo-1593501720849-052a65463f6a?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-20',
    name: 'Travessa de Vidro',
    description: 'Transparência para servir com elegância.',
    image: 'https://images.unsplash.com/photo-1551060965-db14995f2e62?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-21',
    name: 'Chaleira Elétrica',
    description: 'Água quente em segundos para o chá da tarde.',
    image: 'https://images.unsplash.com/photo-1563821033-6688536cb472?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-22',
    name: 'Conjunto de Potes',
    description: 'Organização hermética para a despensa.',
    image: 'https://images.unsplash.com/photo-1589360829809-5b77de564756?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-23',
    name: 'Potes de Tempero',
    description: 'O segredo do sabor sempre à mão.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-24',
    name: 'Jarras',
    description: 'Para servir refrescos com estilo.',
    image: 'https://images.unsplash.com/photo-1591107561284-ee92209dd7d0?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-25',
    name: 'Sanduicheira',
    description: 'Lanches rápidos e crocantes.',
    image: 'https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-26',
    name: 'Grill',
    description: 'Grelhados saudáveis e suculentos.',
    image: 'https://images.unsplash.com/photo-1555529733-0e670560f7e1?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-27',
    name: 'Batedeira',
    description: 'Para criar bolos fofinhos e memórias.',
    image: 'https://images.unsplash.com/photo-1576620593739-12294247556a?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-28',
    name: 'Cafeteira',
    description: 'Aroma de café fresco para começar o dia.',
    image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-29',
    name: 'Panela de Arroz',
    description: 'Arroz soltinho com praticidade total.',
    image: 'https://images.unsplash.com/photo-1586546376510-9118c7c999b1?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-30',
    name: 'Fruteira',
    description: 'Cores e saúde decorando a cozinha.',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  },
  {
    id: 'cz-31',
    name: 'Escorredor de Louça',
    description: 'Organização essencial após as refeições.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    category: 'Cozinha',
    claimedBy: null,
    claimedByUserId: null,
  }
];